import Head from "next/head";
import { useRouter } from "next/router";
import { FC, PropsWithChildren } from "react";
import { main } from "../locales/main";

const AdminLayout: FC<PropsWithChildren> = (props) => {
  const { children } = props;
  const router = useRouter();
  const locale = router.locale || "ru";
  return (
    <>
      <Head>
        <title>{main[locale].admin}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>AdminLayout Header</header>
      <main>{children}</main>
    </>
  );
};

export default AdminLayout;
