import { Session } from "@supabase/supabase-js";
import Head from "next/head";
import { useRouter } from "next/router";
import { FC, PropsWithChildren, useEffect, useState } from "react";
import styled from "styled-components";
import Footer from "../components/Footer";
import HeaderAdmin from "../components/HeaderAdmin";
import AuthListener from "../components/AuthListener";
import { supabase } from "../helpers/supabase";
import { main } from "../locales/main";

const AdminContainer = styled.main`
  padding: 24px 0;
  flex: 1 1 auto;
  width: 100%;
  max-width: 1140px;
  margin: 0 auto;
`;

const AdminLayout: FC<PropsWithChildren> = (props) => {
  const { children } = props;
  const router = useRouter();
  const locale = router.locale || "ru";
  const [session, setSession] = useState<Session | null>(null);

  const getSession = async () => {
    const { data } = await supabase.auth.getSession();
    setSession(data.session);
  };

  useEffect(() => {
    getSession();
  }, []);

  return (
    <>
      <Head>
        <title>{main[locale].admin}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthListener accessToken={session?.access_token} />
      <HeaderAdmin />
      <AdminContainer>{children}</AdminContainer>
      <Footer />
    </>
  );
};

export default AdminLayout;
