import Head from "next/head";
import { useRouter } from "next/router";
import { FC, PropsWithChildren } from "react";
import styled from "styled-components";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { main } from "../locales/main";

const MainContainer = styled.main`
  padding: 24px 0;
  flex: 1 1 auto;
`;

const MainLayout: FC<PropsWithChildren> = (props) => {
  const { children } = props;
  const router = useRouter();
  const locale = router.locale || "ru";
  return (
    <>
      <Head>
        <title>{main[locale].title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainContainer>{children}</MainContainer>
      <Footer />
    </>
  );
};

export default MainLayout;
