import Head from "next/head";
import { useRouter } from "next/router";
import { FC, PropsWithChildren } from "react";
import Footer from "../components/Footer";
import { main } from "../locales/main";

const MainLayout: FC<PropsWithChildren> = (props) => {
  const { children } = props;
  const router = useRouter();
  const locale = router.locale || "ru";
  return (
    <>
      <Head>
        <title>{main[locale].title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>MainLayout Header</header>
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default MainLayout;
