import Head from "next/head";
import { NextPage } from "next";
import { useRouter } from "next/router";
import Title from "../components/Title";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Journal 29 Hints</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>Welcome to Journal 29 Hints!</Title>
      <p>Locale: {router.locale}</p>
    </>
  );
};

export default Home;
