import Head from "next/head";
import { NextPage } from "next";
import { useRouter } from "next/router";
import Title from "../components/Title";
import { main } from "../locales/main";

const Home: NextPage = () => {
  const router = useRouter();
  const locale = router.locale || "ru";
  return (
    <>
      <Head>
        <title>{main[locale].title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>
        {main[locale].welcome} {main[locale].title}!
      </Title>
      <p>
        {main[locale].locale} {locale}
      </p>
    </>
  );
};

export default Home;
