import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Journal 29 Hints</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Next.js!</h1>
      </main>
    </div>
  );
};

export default Home;
